apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
  - name: workspace
  tasks:
    - name: git-clone
      params:
       - name: url
         value: "https://github.com/babulalt/one-time-secret.git"
       - name: revision
         value: "pipeline-sucess"
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: git-clone