apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: slack-notification
spec:
  params:
    - name: webhook-secret
      type: string
      description: secret name of the slack app webhook URL (key is url)
    - name: message
      type: string
      description: plain text message
    - name: bot-name
      type: string
      description: plain text message
      default: project
    - name: icon-emoji
      type: string
      description: plain text message
      default: ":robot_face:"
  steps:
    - name: post
      image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4
      script: >
        #!/usr/bin/env sh
        MESSAGE=$(echo "${MESSAGE}" | sed -e 's/\"/\\\\"/g')
        BOTNAME=$(echo "${BOTNAME}" | sed -e 's/\"/\\\\"/g')
        JSON="{\"text\": \"$(params.message)\", \"username\": \"$(params.bot-name)\", \"icon_emoji\": \"${EMOJI}\"}"
        curl -X POST -H 'Content-Type: application/json' --data "${JSON}" "${SLACK_URL}"
      env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: $(params.webhook-secret)
              key: url
  
