apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: kubernetes-actions-
spec:
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        echo "----------"
        kubectl get deployment
  workspaces:
    - name: kubeconfig-dir
      emptyDir: {}
    - name: manifest-dir
      emptyDir: {}
  serviceAccountName: tekton-pipeline